# Programmation fonctionnelle sur R

## Motivation

Considérons de problème suivant: vous avez fini de nétoyer vos données et vous voulez avoir un résumé des variables. Vous pourez écrire un code qui resemblait à ça

In [ ]:
mean(df$a)
median(df$a)
sd(df$a)
IQR(df$a)

mean(df$b)
median(df$b)
sd(df$b)
IQR(df$b)
.
.
.
ect

Une autre consist à écrire une fonction résumé qui sera appliqué à toutes les variables. C'est plus efficace

In [10]:
summary <- function(x) {
  c(mean(x), median(x), sd(x), IQR(x))
}
head(mtcars)
dim(mtcars)

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

[1] 32 11

In [8]:
lapply(mtcars, summary)

$mpg
[1] 20.090625 19.200000  6.026948  7.375000

$cyl
[1] 6.187500 6.000000 1.785922 4.000000

$disp
[1] 230.7219 196.3000 123.9387 205.1750

$hp
[1] 146.68750 123.00000  68.56287  83.50000

$drat
[1] 3.5965625 3.6950000 0.5346787 0.8400000

$wt
[1] 3.2172500 3.3250000 0.9784574 1.0287500

$qsec
[1] 17.848750 17.710000  1.786943  2.007500

$vs
[1] 0.4375000 0.0000000 0.5040161 1.0000000

$am
[1] 0.4062500 0.0000000 0.4989909 1.0000000

$gear
[1] 3.6875000 4.0000000 0.7378041 1.0000000

$carb
[1] 2.8125 2.0000 1.6152 2.0000

## Les fonctions annonymes

Les fonctions annonymes sont des fonctions qui n'ont pas de nom. On utilise ces fonctions lorsqu'il n'est pas necessaire nommer la fonction avant de l'utiliser

In [13]:
res=lapply(mtcars, function(x){length(unique(x))})

typeof(res)

[1] "list"

In [14]:
Filter(function(x) !is.numeric(x), mtcars)


Mazda RX4          
Mazda RX4 Wag      
Datsun 710         
Hornet 4 Drive     
Hornet Sportabout  
Valiant            
Duster 360         
Merc 240D          
Merc 230           
Merc 280           
Merc 280C          
Merc 450SE         
Merc 450SL         
Merc 450SLC        
Cadillac Fleetwood 
Lincoln Continental
Chrysler Imperial  
Fiat 128           
Honda Civic        
Toyota Corolla     
Toyota Corona      
Dodge Challenger   
AMC Javelin        
Camaro Z28         
Pontiac Firebird   
Fiat X1-9          
Porsche 914-2      
Lotus Europa       
Ford Pantera L     
Ferrari Dino       
Maserati Bora      
Volvo 142E

In [15]:
integrate(function(x) sin(x) ^ 2, 0, pi)

1.570796 with absolute error < 1.7e-14

## Closures

ce sont des fonctions qui renvoient une fonction comme resultat

In [16]:
power <- function(exponent) {
  function(x) {
    x ^ exponent
  }
}


In [19]:
carre=power(2)
carre(2)
carre(8)

[1] 4

[1] 64

In [23]:
cube=power(3)
cube(2)
cube(4)

[1] 8

[1] 64

In [24]:
bc <- function(lambda) {
  if (lambda == 0) {
    function(x) log(x)
  } else {
    function(x) (x ^ lambda - 1) / lambda
  }
}

In [25]:
f1=bc(0)
f1(1)

[1] 0

In [27]:
f2=bc(1)
f2(2)

[1] 1

## la famille Apply

**` apply()`**

Renvoie un vecteur ou un tableau ou une liste de valeurs obtenues en appliquant une fonction aux marges d'un array ou d'une matrice

`apply(X, MARGIN, FUN, …)`

In [29]:
mymatrix<-matrix(1:9,nrow=3)
mymatrix

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [30]:
apply(mymatrix,1,sum) #somme des lignes

[1] 12 15 18

In [31]:
apply(mymatrix,2,sum) #somme des colonnes

[1]  6 15 24

In [32]:
# on peut aussi inclure les arguments de la fonction
apply(mymatrix,1,sum,na.rm=TRUE)

[1] 12 15 18

**`lapply()`**

syntaxe : `lapply(X, FUN,…)`

lapply renvoie une <font color="red">liste</font> de même longueur que X, dont chaque élément est le résultat de l'application de FUN à l'élément correspondant de X.

<font color="red">Pas besoin de marges</font>

In [34]:
mylist<-list(A=matrix(1:9,nrow=3),B=1:5,C=8)
mylist


$A
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

$B
[1] 1 2 3 4 5

$C
[1] 8

In [35]:
lapply(mylist,sum)

$A
[1] 45

$B
[1] 15

$C
[1] 8

In [36]:
unlist(lapply(mylist,sum))

A  B  C 
45 15  8

avec une fonction annonyme

In [37]:
lapply(mylist,function(x){x-2})

$A
     [,1] [,2] [,3]
[1,]   -1    2    5
[2,]    0    3    6
[3,]    1    4    7

$B
[1] -1  0  1  2  3

$C
[1] 6

**`sapply()`**

sapply est une version conviviale de lapply qui retourne par défaut un vecteur, une matrice ou, si simplify = "array", un tableau si nécessaire, en appliquant simplify2array().

`sapply(x, f, simplify = FALSE, USE.NAMES = FALSE)`  est la même chose que `lapply(x, f)`

In [38]:
sapply(mylist,sum)

A  B  C 
45 15  8

**`mapply()`**

m représente multi-variante apply.



In [39]:
x<-c(A=20,B=1,C=40)
y<-c(J=430,K=50,L=10)

simply<-function(u,v){
  (u+v)*2
}
mapply(simply,x,y)

A   B   C 
900 102 100

**`tapply()`**

Appliquez une fonction à chaque cellule d'un tableau en escalier, c'est-à-dire à chaque groupe (non vide) de valeurs données par une combinaison unique des niveaux de certains facteurs.

In [41]:
head(iris)
unique(iris$Species)

Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa 
2 4.9          3.0         1.4          0.2         setosa 
3 4.7          3.2         1.3          0.2         setosa 
4 4.6          3.1         1.5          0.2         setosa 
5 5.0          3.6         1.4          0.2         setosa 
6 5.4          3.9         1.7          0.4         setosa

[1] setosa     versicolor virginica 
Levels: setosa versicolor virginica

In [43]:
tapply(iris$Sepal.Length,iris$Species,max)

setosa versicolor  virginica 
       5.8        7.0        7.9

### En résumé

**`apply()`**:- Applique une fonction sur les marges d'un tableau.

**`lapply()`**:- Boucle sur une liste et évalue une fonction sur chaque élément.

**`sapply()`**:- Identique à lapply mais en essayant de simplifier le résultat.

**`mapply()`**:- Version multivariée de lapply

**`tapply()`**:-Applique une fonction sur des sous-ensembles d'un vecteur.

## La famille Map,reduce,walk

In [49]:
#install.packages("purrr")
library(purrr)
help(package=purrr)

# map

Elle prend un vecteur et une fonction, appelle la fonction une fois pour chaque élément du vecteur, et renvoie les résultats dans une liste. En d'autres termes,` map(1:3, f)` est équivalent à `list(f(1), f(2), f(3))`.
<table bgcolor="white">
    <tr><td><img src='https://d33wubrfki0l68.cloudfront.net/f0494d020aa517ae7b1011cea4c4a9f21702df8b/2577b/diagrams/functionals/map.png'>
        </td><td><img src='https://d33wubrfki0l68.cloudfront.net/e1b3536a7556aef348f546a79277125c419a5fdc/0c0a1/diagrams/functionals/map-arg.png'></td>
    <td><img src='https://d33wubrfki0l68.cloudfront.net/a468c847ea8aca9a6131492e1e7431f418259eaf/ce4e0/diagrams/functionals/map-arg-recycle.png'></td></tr>
</table>

In [53]:
triple <- function(x) x * 3
map(1:3, triple)
# possible d'utiliser une fonction annonyme

[[1]]
[1] 3

[[2]]
[1] 6

[[3]]
[1] 9

In [54]:
map(1:3,carre)

[[1]]
[1] 1

[[2]]
[1] 4

[[3]]
[1] 9

In [55]:
puissance=function(x,n){x^n}

map(1:3,puissance,3)

[[1]]
[1] 1

[[2]]
[1] 8

[[3]]
[1] 27

   Et on on crée notre propre fonction map

In [ ]:
simple_map <- function(x, f, ...) {
  out <- vector("list", length(x))
  for (i in seq_along(x)) {
    out[[i]] <- f(x[[i]], ...)
  }
  out
}

Il y'a 4 variantes spécifiques de `map()`: `map_lgl()`, `map_int()`, `map_dbl()`, and `map_chr()`. Chacune retourne un vecteur atomique du type spécifié :

In [56]:
# map_chr() always returns a character vector
map_chr(mtcars, typeof)

mpg      cyl     disp       hp     drat       wt     qsec       vs 
"double" "double" "double" "double" "double" "double" "double" "double" 
      am     gear     carb 
"double" "double" "double"

In [57]:
# map_lgl() always returns a logical vector
map_lgl(mtcars, is.double)

mpg  cyl disp   hp drat   wt qsec   vs   am gear carb 
TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE

In [58]:
# map_int() always returns a integer vector
n_unique <- function(x) length(unique(x))
map_int(mtcars,n_unique)

mpg  cyl disp   hp drat   wt qsec   vs   am gear carb 
  25    3   27   22   22   29   30    2    2    3    6

In [59]:
# map_dbl() always returns a double vector
map_dbl(mtcars, mean)

mpg        cyl       disp         hp       drat         wt       qsec 
 20.090625   6.187500 230.721875 146.687500   3.596563   3.217250  17.848750 
        vs         am       gear       carb 
  0.437500   0.406250   3.687500   2.812500

### des racourcis

In [60]:
head(mtcars)

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

In [76]:
res=map(1:5, ~runif(5))
res
typeof(res)

res1=as.data.frame(do.call("cbind",res))
typeof(res1)
res1

[[1]]
[1] 0.09232988 0.62635683 0.50463782 0.24801544 0.99179846

[[2]]
[1] 0.1768515 0.3689027 0.8622094 0.4034807 0.4114044

[[3]]
[1] 0.6916140 0.1492855 0.8358093 0.2861819 0.1809849

[[4]]
[1] 0.6287780 0.3152268 0.8862531 0.2569771 0.4288503

[[5]]
[1] 0.05093341 0.02816190 0.12830652 0.85538055 0.13106897

[1] "list"

[1] "list"

V1         V2        V3        V4        V5        
1 0.09232988 0.1768515 0.6916140 0.6287780 0.05093341
2 0.62635683 0.3689027 0.1492855 0.3152268 0.02816190
3 0.50463782 0.8622094 0.8358093 0.8862531 0.12830652
4 0.24801544 0.4034807 0.2861819 0.2569771 0.85538055
5 0.99179846 0.4114044 0.1809849 0.4288503 0.13106897

In [4]:
plus <- function(x, y) x + y

x <- c(0, 0, 0, 0)
map_dbl(x, plus, 3)

ERROR: Error in map_dbl(x, plus, 3): impossible de trouver la fonction "map_dbl"


## map2

<table bgcolor="white">
    <tr><td><img src='https://d33wubrfki0l68.cloudfront.net/f5cddf51ec9c243a7c13732b0ce46b0868bf8a31/501a8/diagrams/functionals/map2.png'>
        </td><td><img src='https://d33wubrfki0l68.cloudfront.net/7a545699ff7069a98329fcfbe6e42b734507eb16/211a5/diagrams/functionals/map2-arg.png'></td></tr>
</table>

In [79]:
xs=1:10
ws=1:10
map2_dbl(xs, ws,function(x,y){x+y})

[1]  2  4  6  8 10 12 14 16 18 20

### pmap

<table bgcolor="white">
    <tr><td><img src='https://d33wubrfki0l68.cloudfront.net/e426c5755e2e65bdcc073d387775db79791f32fd/92902/diagrams/functionals/pmap.png'>
        </td><td><img src='https://d33wubrfki0l68.cloudfront.net/2eb2eefe34ad6d114da2a22df42deac8511b4788/5a538/diagrams/functionals/pmap-arg.png'></td>
    <td><img src='https://d33wubrfki0l68.cloudfront.net/e698354d802ce16f83546db63c45a19b8d51f45e/43de7/diagrams/functionals/pmap-3.png'></td></tr>
</table>


In [81]:
xs=1:10
ws=1:10
t=11:20
pmap(list(xs, ws,t),function(x,y,k){x+y+k})

[[1]]
[1] 13

[[2]]
[1] 16

[[3]]
[1] 19

[[4]]
[1] 22

[[5]]
[1] 25

[[6]]
[1] 28

[[7]]
[1] 31

[[8]]
[1] 34

[[9]]
[1] 37

[[10]]
[1] 40

## walk

<table bgcolor="white">
    <tr><td><img src='https://d33wubrfki0l68.cloudfront.net/d16783978b0d33756af9951ad3fba2596eb8e934/233ba/diagrams/functionals/walk.png'>
        </td><td><img src='https://d33wubrfki0l68.cloudfront.net/19d5f7d265107c81dded3e98319d48ec01821308/b8621/diagrams/functionals/walk2.png'></td></tr>
</table>

Pas besoin de sortie



In [83]:
welcome <- function(x) {
  cat("Welcome ", x, "!\n", sep = "")
}
names <- c("Elize", "Khady")

map(names, welcome)

walk(names,welcome)


Welcome Elize!
Welcome Khady!


[[1]]
NULL

[[2]]
NULL

Welcome Elize!
Welcome Khady!


In [84]:
unique(iris$Species)

[1] setosa     versicolor virginica 
Levels: setosa versicolor virginica

In [86]:
temp <- tempfile()
dir.create(temp)

cyls <- split(iris, iris$Species)

typeof(cyls)

[1] "list"

In [88]:
paths <- file.path(temp, paste0("cyl-", names(cyls), ".csv"))
paths

[1] "C:\\Users\\USER\\AppData\\Local\\Temp\\Rtmp4gMgnv\\file5b44229c3f42/cyl-setosa.csv"    
[2] "C:\\Users\\USER\\AppData\\Local\\Temp\\Rtmp4gMgnv\\file5b44229c3f42/cyl-versicolor.csv"
[3] "C:\\Users\\USER\\AppData\\Local\\Temp\\Rtmp4gMgnv\\file5b44229c3f42/cyl-virginica.csv"

In [89]:
walk2(cyls, paths, write.csv)

In [90]:
dir(temp)

[1] "cyl-setosa.csv"     "cyl-versicolor.csv" "cyl-virginica.csv"

Ici le walk2() est équivalent à `write.csv(cyls[[1]], paths[[1]])`, `write.csv(cyls[[2]], paths[[2]])`, `write.csv(cyls[[3]], paths[[3]])`.

# Reduce
reduce() prend un vecteur de longueur n et produit un vecteur de longueur 1 en appelant une fonction avec une paire de valeurs à la fois : `reduce(1:4, f)` est équivalent à `f(f(f(1, 2), 3), 4)`.

<table bgcolor="white">
    <tr><td><img src='https://d33wubrfki0l68.cloudfront.net/9c239e1227c69b7a2c9c2df234c21f3e1c74dd57/eec0e/diagrams/functionals/reduce.png'>
        </td><td><img src='https://d33wubrfki0l68.cloudfront.net/3f81c662fd1b426d7ce21e9369a10adcaa776272/f4809/diagrams/functionals/reduce-arg.png'></td></tr>
</table>

Pas besoin de sortie



In [92]:
l <- map(1:4, ~ sample(1:10, 15, replace = T))
l

[[1]]
 [1]  6  2  1  6  4  7  1  7  8 10  8  1  2  1  6

[[2]]
 [1]  3  1 10  3  3  2  2  5  6  8  4  4  5  5  5

[[3]]
 [1]  7  1  4  6 10  4  1  2  2  8  6 10  5  5  7

[[4]]
 [1]  2  3  3  2  9  8  8  3  9  6 10  7 10 10  2

In [94]:
reduce(l,intersect)
reduce(l,union)

[1]  6  2  8 10

[1]  6  2  1  4  7  8 10  3  5  9

### accumulate
La première variante de reduce(), accumulate(), est utile pour comprendre le fonctionnement de reduce, car au lieu de renvoyer uniquement le résultat final, elle renvoie également tous les résultats intermédiaires :

In [95]:
accumulate(l, intersect)

[[1]]
 [1]  6  2  1  6  4  7  1  7  8 10  8  1  2  1  6

[[2]]
[1]  6  2  1  4  8 10

[[3]]
[1]  6  2  1  4  8 10

[[4]]
[1]  6  2  8 10

In [96]:

x <- c(4, 3, 10)
reduce(x, `+`)

accumulate(x, `+`)

[1] 17

[1]  4  7 17